### ISSUE TITLE
functions only app

### ISSUE THREAD

**Issue by zpydee** [simondotm/nx-firebase#107]
it would be great to have a flag for a functions only app, which would remove bootstrapping for firestore, storage, hosting etc.

Thoughts?

**Comment by simondotm** [comment]
@zpydee great idea and I'm actually in the middle of writing that exact feature! I've moved over to bundles for my own functions and its a much better experience.

**Comment by zpydee** [comment]
Ps, thanks for this lib. Really great.  To date, I've been following a method [described here](https://itnext.io/nx-nest-firebase-the-dream-616e8ee71920), but it's failed me with firebase's famous CORS warning when using callable functions. Just sharing for your interest in case it adds any value...

**Comment by simondotm** [comment]
I gave up on callables and just went with request functions and express APIs. Callables seemed convenient on the client side at first, but I ended up boilerplating an API of sorts in the callable function anyway, and its fairly trivial to pass the JWT in the auth headers than can verified function side with firebase auth lib.
I think CORs issues exist on every web project at some point tbh! 😆

**Comment by zpydee** [comment]
"I think CORs issues exist on every web project at some point tbh" - true that :-)

**Comment by simondotm** [comment]
Will be possible in #116
