### ISSUE TITLE
Module '@mymono/typescript-interfaces' Not Found

### ISSUE THREAD

**Issue by aureliopetrone** [simondotm/nx-firebase#120]
I'm encountering an issue where the module '@mymono/typescript-interfaces', which is a buildable package containing TypeScript interfaces, cannot be found or its corresponding type declarations.

### Steps to reproduce:

Installed nx
Installed latest  version of simondotm/nx-firebase
Attempted to import { Activity } from "mymono/typescript-interfaces"

### Error Message

```
Cannot find module '@mymono/typescript-interfaces' or its corresponding type declarations.

6 import { Activity } from "@mymono/typescript-interfaces"
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
### Expected behavior:
The 'mymono/typescript-interfaces' module should be found and the application should compile without errors.

### Additional context:
The 'mymono/typescript-interfaces' is a buildable package containing TypeScript interfaces. If there's any further information required or if I've missed any steps that might cause this issue, please let me know.

 Node : 16.16.0
   OS   : darwin arm64
   yarn : 3.4.1
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : 15.3.3
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.3.3
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.3.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : 15.3.3
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @simondotm/nx-firebase: 1.0.0

**Comment by aureliopetrone** [comment]
This i happening also with nx 15.3.3 and nx-firebase 1.0.0

**Comment by simondotm** [comment]
This sounds like a workspace config issue rather than a plugin issue.
Check your `typescript-interfaces` library was created with `--importPath=@mymono/typescript-interfaces`

**Comment by aureliopetrone** [comment]
I have 4 apps in the monorepo (and around 10 libraries) building fine that uses that shared library. It "--importPath=@mymono/typescript-interfaces" necessary only for nx-cloud?

**Comment by aureliopetrone** [comment]
So, I found the issue. In project.json inside the typescript shared lib, this is not working:

<img width="518" alt="Screenshot 2023-06-25 at 15 06 15" src="https://github.com/simondotm/nx-firebase/assets/12773128/d0227749-894d-4c8f-9523-714d14aeaedb">

If you remove "rootDir" it start to working. 

<img width="575" alt="Screenshot 2023-06-25 at 15 06 27" src="https://github.com/simondotm/nx-firebase/assets/12773128/4e042731-cabb-4b08-a354-f32713b2efbb">

I wonder why the rest of the packages were building fine. Is it because they didn't need the compiled library but the original typescript one?

**Comment by simondotm** [comment]
Yeah thats odd. I've rarely, if ever, seen `rootDir` set in a project config.
Just a thought, but perhaps if your other packages are using bundlers, they probably just use the source Typescript to build rather than the compiled JS so would be unaffected by this setting.

Glad you got it sorted.
FWIW there'll be a new 2.0 version of the firebase plugin soon that no longer needs libraries to be buildable. 👍
