### ISSUE TITLE
Cloud Function Deployment Issue: "nx not found"

### ISSUE THREAD

**Issue by aureliopetrone** [simondotm/nx-firebase#121]
When attempting to deploy a Cloud Function, I encounter an issue where the system is unable to find "nx". This happens because of the execution of the package.json build script. I believe there might be an option to deploy the function after building it locally, but I'm not certain.

### Steps to reproduce:

Attempt to deploy a Cloud Function.

### Error Message:

`Cannot find "nx". 
`
### Expected behavior:

The build script in package.json should execute locally I guess. The Cloud Function should then be deployed successfully.

### Additional context:

If there's a way to deploy the function after building it locally, that information would be helpful. If I've missed any steps that might lead to this issue or if further information is required, please let me know.

 Node : 16.16.0
   OS   : darwin arm64
   yarn : 3.4.1
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : 15.3.3
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : 15.3.3
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.3.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : 15.3.3
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @simondotm/nx-firebase: 1.0.0

**Comment by simondotm** [comment]
Try `npx nx`

**Comment by aureliopetrone** [comment]
I mean the build works locally. That error happens on cloud, because is trying to execute the build script present in package.json, but since nx is not available it fails.

**Comment by aureliopetrone** [comment]
For example, changing build to build: "local" on the generated package.json after the building, and deploying manually works

**Comment by aureliopetrone** [comment]
Adding 
```
 "scripts": {
     ...
    "gcp-build":""
  },
```
To the scripts in package.json solve the issue.

**Comment by simondotm** [comment]
Ok great work. In all honesty I'm not fully understanding this issue, but glad to hear you resolved it.

**Comment by aureliopetrone** [comment]
@simondotm Essentially, what happens is that GCloud is designed to automatically execute your build script upon package upload. The problem you're encountering arises because your build script relies on "nx", a tool you have installed on your local machine. Unfortunately, "nx" is not present in the GCloud environment, causing your build script to fail when executed there.

Google Cloud Platform allows you to customize your build process by providing an alternative to the default build script. You can leverage this feature to overcome the current problem. What you essentially need to do is create a custom "gcp-build" script that can run in the GCloud environment without needing the "nx".

The "gcp-build" script serves as an override to the default build script. So when you upload your package, GCloud will recognize the presence of this "gcp-build" script and use it in place of the regular build script that is suited to your local environment. By customizing your build process in this way, you can ensure that the script is compatible with the tools and utilities available on GCloud, and thereby avoid the issues that arise due to the absence of "nx".

This approach would allow you to continue using "nx" for local builds while also maintaining a compatible build process for your deployments to GCloud.
