### ISSUE TITLE
Importing other libraries types and constants not linked

### ISSUE THREAD

**Issue by pikilon** [simondotm/nx-firebase#129]
I import them and it compiles (despite TSC should break on compilation) but I can't do type checking and my IDE is not helping me with the imported constants.

![image](https://github.com/simondotm/nx-firebase/assets/3034213/e3f6e62a-90da-4697-be63-936c185f1190)

I am using "^2.0.0-beta.1" and nx v16.5.1 and the latest firebase functions.

Thanks you again

**Comment by simondotm** [comment]
@pikilon - hmm perhaps VSCode's Typescript service isn't detecting the library alias from `tsconfig.base.json`

Try reloading your window or restarting the Typescript server ?

**Comment by pikilon** [comment]
I tried but it didn't work, maybe the tsconfig.app.json is confusing VSC?

**Comment by simondotm** [comment]
does the esbuild .js output in `dist` from building the function look ok?

**Comment by simondotm** [comment]
That's really strange. I just added the code above to a boilerplate function I generated with the plugin and I do get a TS compilation error:

![image](https://github.com/simondotm/nx-firebase/assets/7404321/10e3660f-22f9-42b7-bd91-5348481556c7)

**Comment by simondotm** [comment]
> My main target on the typing is to share models with the frontend.

Yes of course. I use shared libraries just for models too and it works nicely with my backend / frontend projects.
So I'm not sure what's going on with you.

`tsconfig.app.ts` for my function is the default generator output:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../../../dist/out-tsc",
    "module": "es2020",
    "types": ["node"],
    "target": "es2020"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

I'm using 16.1.1 of Nx however. I wonder if something has changed... 🤔

**Comment by pikilon** [comment]
> That's really strange. I just added the code above to a boilerplate function I generated with the plugin and I do get a TS compilation error:
> 
> ![image](https://user-images.githubusercontent.com/7404321/254069613-10e3660f-22f9-42b7-bd91-5348481556c7.png)

I see the same VSC typing error but it does compile:
![image](https://github.com/simondotm/nx-firebase/assets/3034213/8a4bed6f-fc4c-49bd-9afa-84f56edeedaa)

I execute `yarn nx run cloud-functions:build --skip-nx-cache=true `  in the root of the nx workspace and I get this
![image](https://github.com/simondotm/nx-firebase/assets/3034213/85b6ba49-3f63-4e00-b419-10a6a607d7f9)

**Comment by pikilon** [comment]
> {
>   "extends": "./tsconfig.json",
>   "compilerOptions": {
>     "outDir": "../../../../dist/out-tsc",
>     "module": "es2020",
>     "types": ["node"],
>     "target": "es2020"
>   },
>   "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
>   "include": ["src/**/*.ts"]
> }

I see you have nested the cloud-functions folder app inside another project. I have it on the root:
- apps
  - cloud-functions
  - firebase
  - ...
 
 Could be the structure affecting this?

**Comment by simondotm** [comment]
> Could be the structure affecting this?

I can't think of a reason why that would be an issue.

You haven't somehow got `skipTypeCheck` enabled on your function `project.json` `build` target options by any chance?
https://nx.dev/packages/esbuild/executors/esbuild#skiptypecheck

If this is set to true in my test function, I see the same issue as you - esbuild succeeds even though there are TS errors in the code.

Or possibly there's a bug in the latest Nx version related to this option 🤔

**Comment by pikilon** [comment]
I added to the project.json in cloud-functions and even in firebase apps. Still compiling.

I have updated nx today to v16.5.2, still the same.

I think I am going to start a new demo workspace only with this functionality and check if it works, then compare the differences.
I will let you know the results

**Comment by pikilon** [comment]
I have started a new project (today is on version v16.5.3) and it breaks, I will try to fix my older (upgraded many times) installation and bring back the results here if anyone has the same problem

**Comment by pikilon** [comment]
I feel very stupid, for some reason, there was a 2 on every src file in `apps/cloud-functions/tsconfig.app.json`
```json
  "exclude": ["jest.config.ts", "src2/**/*.spec.ts", "src2/**/*.test.ts"],
  "include": ["src2/**/*.ts"]
  ```

I am sorry to bother you with this error.

I finally achieved what I wanted, type the `onCall` functions names (and more in the future). 
This will prevent any typo on the functions and consistency between backend and frontend

This is an example if someone wants to use it.

In types-constants package:
```ts
export type SearchFunctionName = 'search'

export const FUNCTIONS: Record<string, SearchFunctionName | OtherFunctionName> = {
  SEARCH: 'search
}
```

in the cloud-functions search module
```ts
Import { SearchFunctionName } from '@my-nx-project/types-constants'
import { onCall } from 'firebase-functions/v2/https'

const nameCheck: Record<SearchFunctionName, any> = {
  search: onCall(async (request) => { /* ... */ }
}

export { search } from nameCheck;
```

In the frontend
```
import { FUNCTIONS } from '@my-nx-project/types-constants'
import { getFunctions, httpsCallable } from 'firebase/functions'
// ...
export const fbFunctions = getFunctions(app)

export const searchHunts = httpsCallable(fbFunctions, FUNCTIONS.SEARCH)
```
