### ISSUE TITLE
How to authenticate commands in CI

### ISSUE THREAD

**Issue by kdawgwilk** [simondotm/nx-firebase#134]
I am trying to setup deployments on merge and I created a service account that output to a file in github actions and then run the `nx deploy` command while setting the `GOOGLE_APPLICATION_CREDENTIALS` env var to the service account json file to use for auth but it fails with 
```
Error: Failed to authenticate, have you run firebase login?
```

**Comment by simondotm** [comment]
Hi @kdawgwilk  - you need to set a `FIREBASE_TOKEN` variable in your CI environment. 
More Info here 👍 
https://firebase.google.com/docs/cli#cli-ci-systems

**Comment by kdawgwilk** [comment]
From what I have found on the Interwebs 😅 that flow is deprecated https://stackoverflow.com/questions/75653962/firebase-token-deprecated-in-ci-cd-gitlab

**Comment by simondotm** [comment]
ah ok thats good to know, will have to keep an 👀 on that then!
so although its warning that its deprecated, it'll still work for now anyway I guess 👍
