### ISSUE TITLE
error create func

### ISSUE THREAD

**Issue by gui8515** [simondotm/nx-firebase#144]
![image](https://github.com/simondotm/nx-firebase/assets/4814944/9ec5b64a-a671-496c-8ab0-00bf706cc68e)

**Comment by simondotm** [comment]
Thanks for reporting. Looks similar to #131 which I am unable to reproduce.
Please could you run `nx report` and post back here?

**Comment by simondotm** [comment]
Closing this for now. If anyone sees a similar issue occur, please raise a new issue.
