### ISSUE TITLE
List plugin in nx plugin registry

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [simondotm/nx-firebase#145]
We're looking into moving our project to NX.
One of the points that we had doubts about how we would be able to solve it was our firebase functions.
This plugin has solved it brilliantly, it has given us everything we need and then some.
Thank you for that.
Is there a reason that the plugin is not listed in the Nx Plugins Registry?
https://nx.dev/extending-nx/registry
I'm sure a lot of people would be helped by this and find their way quicker here.

**Comment by simondotm** [comment]
Hi @LanderBeeuwsaert , thanks for this feedback, its good to know folks find the plugin useful.
And yes, I've been meaning to add the plugin to the Nx community list for a while. Will do that when I get a moment. 👍

**Comment by simondotm** [comment]
We are now listed in the [Nx Plugin Registry](https://nx.dev/plugin-registry)! 🎉 
![image](https://github.com/simondotm/nx-firebase/assets/7404321/01227c16-ef94-4d28-9921-16eeea61b52d)

**Comment by LanderBeeuwsaert** [comment]
@simondotm well then it's time to close this :-)
