### ISSUE TITLE
Document reason why the package is added as a dependency and not a devDependency

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [simondotm/nx-firebase#146]
I'm surprised the "@simondotm/nx-firebase" package is installed as a dependency and not a devDependency.
Is there a reason for this? It could be useful to add the reason to the documentation?

**Comment by simondotm** [comment]
Hi @LanderBeeuwsaert , thanks for the feedback.
You are correct, the documentation should recommend the plugin is installed as a devDependency. Good spot!
