### ISSUE TITLE
v2.1.1 Release

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#154]
Ok, that was a drama. v2.1.1 release is now the latest from npm with fixes to v2.1.0 (which should be considered a broken release).

You can run `npx nx g @simondotm/nx-firebase:migrate` to update your workspace to the latest 2.1.1 schemas.

These recent feature updates have been fairly tricky, but I think we're good now.

Please share here if any problems arise.

**Comment by adamstret** [comment]
Hello Simon,
can I ask you a question about a thing or two regarding the function generator?

**Comment by adamstret** [comment]
In the **<function-name>/project.json** file the functions generator generates
```
"lint": {
      "executor": "@nx/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/test-sdm-fire-function/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/test-sdm-fire-function/jest.config.ts",
        "passWithNoTests": true
      },
      "configurations": {
        "ci": {
          "ci": true,
          "codeCoverage": true
        }
      }
    },
```

... I was wondering about
**"lint":"lintFilePatterns"**
and 
**"test":"configurations"**
I don't see them declared in any of the generator files.
Can you please tell me how you generated those two blocks of code?

**Comment by simondotm** [comment]
The @nx/node generator takes care of those. 
When you run `nx g @simondotm/nx-firebase:function` the plugingenerates a customised `@nx/node` app project.
