### ISSUE TITLE
Dependency conflicts since nx version `16.8.1`  

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#155]
Hey Simon I am working with nx version `16.8.1`  and I had a problem that I fixed in the end.
**Steps to reproduce**
* nx version `16.8.1` 
* Install "@simondotm/nx-firebase": "^2.1.0"
* Create a functions firebase app with your extension
* `package.json` got modified with     "esbuild": "^0.17.17"

**Current behaviour**
You can't run `npm install` any longer for a conflict between esbuild and "@nx/esbuild": "16.8.1",

**My fix**
In my case I have to change the version of  "esbuild": "^0.17.17" to `"esbuild": "^0.19.2"` 

> If I removed esbuild = no more compilations of the functions

I hope it could help the next one.

Than you for your work @simondotm !!

_Originally posted by @pikilon in https://github.com/simondotm/nx-firebase/issues/151#issuecomment-1733714532_

**Comment by simondotm** [comment]
Not gonna lie - this one is a headache. Not sure why this happens or how to fix it. 😕

**Comment by pikilon** [comment]
While it's works (and does) it is ok

**Comment by mjbates7** [comment]
@simondotm fyi I had this issue I raised with the nx team on their discord (and someone else did on their GH) and it looks like they've now fixed it: https://github.com/nrwl/nx/pull/19728

**Comment by simondotm** [comment]
@mjbates7 ok thats good news, thanks for sharing this.
I guess this means we will all have to update Nx again in our workspaces, and that Nx versions 16.8.1 thru to whichever nx release that fix arrives will be incompatible for us nx-firebase plugin users. 😕

**Comment by mjbates7** [comment]
Seems like it. It's landed in their latest v17.0.0 release https://github.com/nrwl/nx/releases/tag/17.0.0 as a heads up so I'll probably migrate to that now

**Comment by pikilon** [comment]
I have migrated my personal project (NX@16.8.0) to NX@17.0.0 and **everything is fine and fixed**, this is what I did:
* nx run migrations latest and --run-migrations
* removed `esbuild@0.19.4` dependency using `yarn`
* deleted dist, node_modules and yarn.lock
* `npx nx deploy firebase` (including complex `cloud-functions` app)

**Everything deployed correctly**

### Changes introduced by nx migration on nx-firebase projects
In the function app `cloud-functions` I have this change in the project.json (this change is done in all the projects in the workspace)
**From**
```json
    "lint": {
      "executor": "@nx/linter:eslint",
```
**To**
```json
    "lint": {
      "executor": "@nx/eslint:lint",
```

I hope this could help in the development, thank you @simondotm keep up the good work

**Comment by simondotm** [comment]
Great news, thanks for the update. Seems like Nx 17 is the way to go then.

@pikilon thanks for the migration note too. I think we're ok in the plugin because it uses the `@nx/node` plugin to scaffold function apps, which will use whichever Nx version is in the workspace. 

So if already on Nx 17, it should scaffold the app with `@nx/eslint`
With pre-Nx-17, it will scaffold with `@nx/linter` but the Nx migration tool will take care of ensuring nx-firebase function apps stay upto date.

I'm glad I made this change to decouple node app generators in the v2 plugin; the original v1 plugin had its own implementation which would have been a real pain to keep the schemas upto date with the dizzying Nx release cadence. 😅

**Comment by pikilon** [comment]
Sorry to bring bad news, Maybe is only related to my project
https://github.com/simondotm/nx-firebase/issues/163

**Comment by simondotm** [comment]
Closing this issue as resolved.
Plugin users for Nx versions prior to 16.8.1 should update Nx to 17.0.0 or higher.
