### ISSUE TITLE
Feature request: Deploy only one function from a multiple functions app

### ISSUE THREAD

**Issue by pikilon** [simondotm/nx-firebase#160]
**Current behavior**

* You can have multiple functions in a single cloud function `app`
* You can deploy all the functions using this package
* Firebase project (without nx) can deploy only one function using `firebase deploy --only functions:function-name`

**Expected behavior**

* you can deploy only one function within a Firebase app

**Comment by simondotm** [comment]
ah, good scenario, thanks @pikilon . I might have to think about how best to handle this in plugin.

The good news is that you can do this with the Firebase CLI.

Each nx-firebase function app is effectively a codebase, so the magic spell you need to deploy just one function from a codebase collection is:

`npx firebase deploy --only functions:<codebase>:function-name`

where `<codebase>` is whatever name you gave your nx-firebase:function project.

**Comment by simondotm** [comment]
UPDATE: Actually the plugin can in fact do this already, even if you have multiple exports in your `nx-firebase:functions` project, it's similar syntax:

`npx nx deploy <codebase> --only functions:<codebase>:function-name`

As above, where `<codebase>` is whatever name you gave your `nx-firebase:function` project.

**Comment by pikilon** [comment]
> npx firebase deploy --only functions:<codebase>:function-name

Thank you very much, I will use it.
I will try to help you as a tester until I know enough to help you with the code.
Until then here you have 4 coffees 
https://Ko-fi.com/home/coffeeshop?txid=137771cf-a7c6-42ad-9d80-24fe744c5282&mode=public&img=ogiboughtsomeone
