### ISSUE TITLE
automatically detect project to deploy to

### ISSUE THREAD

**Issue by ar7casper** [simondotm/nx-firebase#172]
Maybe I'm missing something, after reading the docs. 
In my mind, if I have two firebase projects setup through this plugin, when I run something like `nx deploy foo-function` it should automatically know which firebase project to deploy to.
Cureently, more often than not, wrong functions get deployed to wrong projects due to human error.

Do you have a solution for that?
If not, how can I help in achieving that?

Thanks.

**Comment by simondotm** [comment]
Hi @ar7casper,

Yes, for each `firebase` project you have, you can set the target Firebase project for it to use when deploying:

```
nx g @simondotm/nx-firebase:sync --app=<firebase-app-project-name> --project=<firebase-cli-project-name>
```

https://github.com/simondotm/nx-firebase/blob/main/docs/nx-firebase-sync.md#changing-firebase-cli-project
