### ISSUE TITLE
Deployment Environments usage

### ISSUE THREAD

**Issue by Lowell20** [simondotm/nx-firebase#181]
Am trying to deploy an app to either a prod or a dev environment (two separate firebase projects)
From the docs, this explanation almost gets me there, but I think I need a clarification

> You can now run:
> 
> nx deploy my-firebase-app for dev deployment
> nx deploy my-firebase-app --prod for production deployment
> Note that your-dev-firebase-project and your-prod-firebase-project must exist as [aliases](https://firebase.google.com/docs/cli#project_aliases) in your .firebaserc file for this to work.

Would this be 2 different nx web apps? 
Or would the same web app get deployed to prod-project with --prod and dev-project without --prod

Based on the same app deploying to different firebase projects, I would think .firebaserc should look like this, but of course this can't work.
```{
  "projects": {
    "default": "",
    "nx-project-name": "your-prod-firebase-project ",
    "nx-project-name": "your-dev-firebase-project"
  },
  "targets": {},
  "etags": {}
}
```

**Comment by Lowell20** [comment]
Using the --prod flag but not deploying to the "production" configuration
`nx deploy my-firebase-app-firebase --prod`
and in `my-firebase-app/firebase/project.json`
```"firebase": {
      "executor": "nx:run-commands",
      "options": {
        "command": "firebase --config=firebase.my-firebase-app-firebase.json --project=firebase-dev-project"
      },
      "configurations": {
        "production": {
          "command": "firebase --config=firebase.my-firebase-app-firebase.json --project=firebase-prod-project"
        }
      }
    },
```

**Comment by simondotm** [comment]
When you have a dev and prod environment setup, you will have to create two firebase projects in your firebase account console - lets call them `your-prod-firebase-project` and `your-dev-firebase-project`

You then need to add these to your `.firebaserc` config with aliased names (unrelated to your Nx project names)

```
  "projects": {
    "default": "",
    "prod": "your-prod-firebase-project ",
    "dev": "your-dev-firebase-project"
  },
```
You only need one nx-firebase project in your Nx workspace, because we're saying we'll want to deploy this nx-firebase project to either `prod` or `dev` depending on the `--prod` configuration.

So your config above is correct (I've just renamed to use the example aliases here):
```
      "executor": "nx:run-commands",
      "options": {
        "command": "firebase --config=firebase.my-firebase-app-firebase.json --project=dev"
      },
      "configurations": {
        "production": {
          "command": "firebase --config=firebase.my-firebase-app-firebase.json --project=prod"
        }
      }
    },
```

Now, when we run `deploy` with `--prod` the Firebase CLI command will use `--project=prod`, so will deploy to your `prod` firebase project, and without `--prod` it will deploy the same Nx project to your `dev` firebase project instead.

See [here](https://firebase.google.com/docs/cli#use_aliases) for more info

**Comment by Lowell20** [comment]
Thanks for the feedback, seem to be getting further along with this but am still running into issues.

running
`nx run nx-project-firebase:firebase deploy --prod`
it seems to be using `dev` instead of `prod` 

also, it is using the alias in .firebaserc, not the firebase project name, the project in firebase would be named `prod-firebase-project`, not just dev or prod

getting following error that contains `account dev@appspot.serviceaccount.com` vs my `prod-firebase-project@appspot.serviceaccount.com` and the console link with `?project=dev` which should be `?project=prod-firebase-project`
```
JSON error trying to load .../.firebaserc
Error: Missing permissions required for functions deploy. You must have permission iam.serviceAccounts.ActAs on service account dev@appspot.gserviceaccount.com.
To address this error, ask a project Owner to assign your account the "Service Account User" role from this URL:
https://console.cloud.google.com/iam-admin/iam?project=dev
```

am using dev and prod as aliases as shown here:
```
{
  "projects": {
    "default": "",
    "prod": "prod-firebase-project",
    "dev": "dev-firebase-project"
  }
}
```
and here:
```
    "firebase": {
      "executor": "nx:run-commands",
      "options": {
        "command": "firebase --config=firebase.nx-project-firebase.json --project=dev"
      },
      "configurations": {
        "production": {
          "command": "firebase --config=firebase.nx-project-firebase.json --project=prod"
        }
      }
    }
```
and here:
```
nx deploy nx-project-firebase --prod
```

**Comment by Lowell20** [comment]
Solved, documenting and closing this issue,

Was able to add configuration options to the deploy target that would then call the firebase target with the needed configuration option, both of these targets are in the app/projectName/firebase/project.json file.
For some reason, probably my lack of understanding, .firebaserc did not seem to be a factor at all.

```
{
  "name": "projectName-firebase",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "targets": {
    "deploy": {
      "executor": "nx:run-commands",
      "dependsOn": [
        "build"
      ],
      "options": {
        "command": "nx run projectName-firebase:firebase deploy"
      },
      "configurations": {
        "production": {
          "command": "nx run projectName-firebase:firebase:production deploy"
        },
        "development": {
          "command": "nx run projectName-firebase:firebase:development deploy"
        }
      }
    },
   "firebase": {
      "executor": "nx:run-commands",
      "options": {
        "command": "firebase --config=firebase.projectName-firebase.json --project=development_firebaseProjectName"
      },
      "configurations": {
        "production": {
          "command": "firebase --config=firebase.projectName-firebase.json --project=production_firebaseProjectName"
        },
        "development": {
          "command": "firebase --config=firebase.projectName-firebase.json --project=development_firebaseProjectName"
        }
      }
    }
  }
}
```
