### ISSUE TITLE
IF 0 NEQ 0 (ECHO Nx requires NodeJS to be available. To install NodeJS and NPM, see: https://nodejs.org/en/download/ .; EXIT 1 )

### ISSUE THREAD

**Issue by Isaak-Marcel** [simondotm/nx-firebase#182]
I am getting this error when creating my workspace 

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>nx g @simondotm/nx-firebase:app clothes-search-firebase --directory=apps/server

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>set path_to_root=C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo\

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>WHERE node  1>nul 2>nul

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>IF 0 NEQ 0 (ECHO Nx requires NodeJS to be available. To install NodeJS and NPM, see: https://nodejs.org/en/download/ .; EXIT 1 )

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>WHERE npm  1>nul 2>nul

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>IF 0 NEQ 0 (ECHO Nx requires npm to be available. To install NodeJS and NPM, see: https://nodejs.org/en/download/ .; EXIT 1 )

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>node C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo\\.nx\nxw.js g @simondotm/nx-firebase:app clothes-search-firebase --directory=apps/server

>  NX  Generating @simondotm/nx-firebase:application

 >  NX   Cannot read properties of undefined (reading 'version')

   Pass --verbose to see the stacktrace.

C:\Users\isfla\Desktop\Companies\clothes-search\clothes-search-github-repo>

**Comment by simondotm** [comment]
@Isaak-Marcel did you ever resolve this? It looks to me like there is something up with your node installation... 🤔

**Comment by Isaak-Marcel** [comment]
Yes I resolved it. Yeah something was wrong with node and I had a bunch of other problems as well with my system. But now it works, I have the extension running 👍 I don't think it was anything wrong with the nx-firebase extension.
