### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by mackelito** [simondotm/nx-firebase#186]
running serve locally works great and now it's time to build and deploy.... 😬

````
> nx run functions:build

node_modules/firebase-admin/lib/app/lifecycle.d.ts:34:57 - error TS1127: Invalid character.

  32 | }
  33 | export declare const defaultAppStore: AppStore;
> 34 | export declare function initializeApp(options?: AppOptio§ns, appName?: string): App;
     |                                                         ^
  35 | export declare function getApp(appName?: string): App;
  36 | export declare function getApps(): App[];
  37 | /**

Found 1 error.
````

The only place where I can find `initializeApp()` is in my main.ts and its commented out...
````
// import { initializeApp } from 'firebase-admin/app';
// initializeApp();
````

Not sure where to start digging... nx reset did not help.

**Comment by simondotm** [comment]
What was the cause of your issue @mackelito ? That `AppOptio§ns` type looks like a dodgy file was written somehow...

**Comment by mackelito** [comment]
Not really sure.. I removed node_modules and did a `npm i`.. then it started working again.. 🤷‍♂️
