### ISSUE TITLE
Serve target needs to build synchronously before launching emulator

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#28]
`serve` process ideally needs to be:
1. build synchronously, then 
2. build --watch & start emulator asynchronously.

**Comment by johngrimsey** [comment]
Nx be able to solve this for you (only tested with the `run-commands` builder):

```
"serve": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      "nx run firebase:build --watch && echo 'WATCHING'",
      "nx run firebase:emulate"
    ],
    "readyWhen": "WATCHING",
    "parallel": true
  }
},
```

**Comment by simondotm** [comment]
Latest plugin version has a (hacky) solution for this so closing.
