### ISSUE TITLE
plugin initializer should add `firebase-tools` as a dev dependency

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#36]
this allows CI systems to `npx firebase ...`
Necessary for github actions that dont use the [firebase action](https://github.com/marketplace/actions/github-action-for-firebase)

**Comment by ciriousjoker** [comment]
This is actually pretty useful, because of issues like this:
- https://github.com/firebase/firebase-tools/issues/4952

**Comment by simondotm** [comment]
as of `0.13.0-beta.0` this is now supported.
