### ISSUE TITLE
Generate nx command for executing tests with emulators running

### ISSUE THREAD

**Issue by Schmale97** [simondotm/nx-firebase#38]
Possible enhancement for nx command in the workspace.json that runs the test command within the firebase emulators:exec command - similar to below?

```json
"testWithEmulatorsRunning": {
    "executor": "@nrwl/workspace:run-commands",
    "options": {
        "command": "nx functions-app:build --with-deps && firebase emulators:exec --project=test 'nx run functions-app:test' --config firebase.functions-app.json"
    }
}
```

**Comment by adrian-marcelo-gallardo** [comment]
@Schmale97 note there is a typo in the command, it should be `nx run functions-app:build` (`run` keyword is missing).

Just for complementing this, and as an alternative config, you can provide both commands (build and run) separate:
```
"testWithEmulatorsRunning": {
    "executor": "@nrwl/workspace:run-commands",
    "options": {
         "commands": [
              {
                "command": "nx run functions-app:build --with-deps"
              },
              {
                "command": "firebase emulators:exec --project=test 'nx run functions-app:test' --config firebase.functions-app.json"
              }
          ]
    }
}
```

**Comment by simondotm** [comment]
Closing due to v2 release and age of issue. Folks, feel free to modify and customise your `project.json` files to suit your workflows! 👍
