### ISSUE TITLE
Missing dependency for @angular-devkit/schematics

### ISSUE THREAD

**Issue by supernaut** [simondotm/nx-firebase#42]
I added nx-firebase to an existing Nx repo with a react app in it. When trying to run the build command for the firebase app it fails with the error:

> Cannot find module '@angular-devkit/schematics'

If I manually add the package to my projects dev-dependencies the build script works.

**Comment by simondotm** [comment]
I believe this would have been a legacy Nx issue, the latest Nx versions have a new CLI and the latest version of the plugin build executor no longer calls `convertNxExecutor` which I _think_ has something to do with the angular devkit.
