### ISSUE TITLE
Update Docs and generated files with `--project=appalias`

### ISSUE THREAD

**Issue by KostasDimakis** [simondotm/nx-firebase#43]
Looks like there might be a neat way to avoid accidental deployment to the wrong target with the use of `--project=appalias`.

More info: https://firebase.google.com/docs/cli#use_aliases

**Comment by simondotm** [comment]
Now Documented here: https://github.com/simondotm/nx-firebase/blob/main/docs/nx-firebase-projects.md#binding-nx-projects-to-firebase-projects
