### ISSUE TITLE
Collaborators requested

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#46]
Hi all. Apologies for the radio silence, lets just say that last year was a rough ride for me and I had to be away from development for a while.

I'm now easing back into things, but first I'd like to delegate ownership of this plugin to the community (something I should have done a while ago, but I didn't realise it was being used by so many folks).

As a start, I've invited @BraunreutherA - author of the recent PR for nx13 compatibility- to be a collaborator on this repo which I hope will allow you all to make progress with a new release of this plugin.

If anyone else would like to be a contributor to this project or you would like to recommend a contributor, please make suggestions below and I will do my best to provide that permission.

I believe everything is setup on github actions for release to npm, I seem to remember it just needs a version tag on master to trigger a publish.

Lastly, I am hoping to continue some some of my own Firebase dev soon and will join you all back in the fray then.

Best,
Simon

**Comment by simondotm** [comment]
I tried a quick merge + release but got a red cross on the CD and I'm out of time to look deeper into this just now. If any new collaborators are able to fix it then that'd be cool otherwise I'll try to revisit again a week or so.

**Comment by shipley-dcc** [comment]
I've created a PR that should fix it.

**Comment by WhatsThatItsPat** [comment]
I don't have anything in particular to say, but it might be worth turning on the Discussions feature for this repo.

**Comment by skylovescoffee** [comment]
I'd be happy to help!

**Comment by simondotm** [comment]
> I don't have anything in particular to say, but it might be worth turning on the Discussions feature for this repo.

I didn't even know about this new GH feature! Thanks for the suggestion. Now done.

**Comment by simondotm** [comment]
Moved to discussion https://github.com/simondotm/nx-firebase/discussions/78
