### ISSUE TITLE
appname:emulate not working

### ISSUE THREAD

**Issue by victorrik** [simondotm/nx-firebase#54]
I like this library and I really plan to use it for future projects, but now I have a problem with the commands.

nx emulate and nx build
Every time I try to use it I get
![Screen Shot 2022-06-27 at 14 02 28](https://user-images.githubusercontent.com/15133959/176017065-ab149d70-324e-4176-a6f8-6a53c2b955a4.png)

![Screen Shot 2022-06-27 at 14 10 02](https://user-images.githubusercontent.com/15133959/176017473-e84a9316-179b-4d9d-9edf-cd3e45e0e4b5.png)

and then, I decided to change the json and only leave the emulators that I want to use and also remove the other commands and it works, but I get that the functions are not loaded

![Screen Shot 2022-06-27 at 14 03 14](https://user-images.githubusercontent.com/15133959/176017522-fd5f329e-0a63-41e5-8d8a-a25280080fc8.png)

![Screen Shot 2022-06-27 at 14 03 59](https://user-images.githubusercontent.com/15133959/176017531-63db1fe5-fc5b-498d-ae36-7631b7856400.png)

and I don't know if in some step I skip any usage requirement because I still tried

**Comment by simondotm** [comment]
Closing this due to age, and also that with v2 the `emulate` target is not for direct use, use `serve` instead.
