### ISSUE TITLE
Firebase Functions deployment issue

### ISSUE THREAD

**Issue by mbrimmer83** [simondotm/nx-firebase#73]
Not a problem with this package, but I wanted to surface it to others who may run into deployment errors since it affects mono-repos in general.

```
[debug] [2022-09-05T11:21:08.962Z] Building nodejs source
[debug] [2022-09-05T11:21:08.963Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-09-05T11:21:08.972Z] Error: spawn ./node_modules/.bin/firebase-functions ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:476:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
[error]
[error] Error: An unexpected error has occurred.
[debug] [2022-09-05T11:21:09.063Z] Serving at port 9005
```

When deploying after upgrading firebase tools, I ran into this [issue](https://github.com/firebase/firebase-tools/issues/4952). I was able to fix deployments by reverting the firebase-tools version.

**Comment by simondotm** [comment]
Thanks, I've seen this happen too. I _think_ it's a node version issue.

**Comment by hendrickson-tyler** [comment]
Thanks for the heads up @mbrimmer83, definitely ran into this issue myself. Specifically for my case, I had to downgrade firebase-tools from 11.19.0 to 11.18.0

**Comment by simondotm** [comment]
Closing as non-plugin related
