### ISSUE TITLE
Failed to deploy because of missing dependencies

### ISSUE THREAD

**Issue by ciriousjoker** [simondotm/nx-firebase#77]
I have a `package.json` in the `apps/myapp` repo.

I had to add these dependencies there into the empty dependency section:

```jsonc
  "dependencies": {
    // this was empty before
    "axios": "^0.27.2",
    "countries-list": "^2.6.1",
    "randomstring": "^1.2.2"
    // ... <- here go most(!) of the dependencies I installed in the top level, but not all.
  },
```

All of these dependencies are already specified in the top level package.json.

Is this expected behavior or a bug? This previously worked (I was using a patched nx-firebase package though).

Some dependencies are copied into the `dist/myapp/package.json` file properly, for example "klaviyo-api", which is definitely not on some sort of whitelist.

**Comment by simondotm** [comment]
Thanks for reporting this @ciriousjoker 
I've seen some odd behaviour like this with my e2e tests, but I am aiming to have a new release of the plugin within the next week or so which I'm hoping will be fixed.

In the meantime, if you could let me know what version of Nx you are using that could be helpful.

**Comment by ciriousjoker** [comment]
Most of the nrwl packages are at either 15.0.0, some a couple patches higher. Can give full list if necessary

**Comment by simondotm** [comment]
Thanks, just that you are on Nx 15+ is useful. I'll post up here when the new plugin version is released, would be great to have someone try it.

**Comment by simondotm** [comment]
@ciriousjoker I am optimistic that this is no longer an issue with the `0.13.0-beta.0` of the plugin, with Nx 13.10.6+

**Comment by simondotm** [comment]
Closing for now. Can open a new issue if we see it happen again.
