### ISSUE TITLE
Next Version Tasks

### ISSUE THREAD

**Issue by simondotm** [simondotm/nx-firebase#85]
Non essential
- [x] See what versions of Nx this new version will be compatible with, since Nx changes so rapidly it's hard to say if versions before 15.3.0 will be compatible
- [ ] #71
- [ ] Support firebase environments
- [x] #63

**Comment by seanaguinaga** [comment]
It doesn't live-reload changes or watch the functions directory, is there a way to fix that?

**Comment by simondotm** [comment]
Yes, the next release is aiming to improve that once I have compatibility testing sorted.

**Comment by algoflows** [comment]
Hey @simondotm I see merges were integrated yesterady but no release was tagged or updated, does this work with the latest version of NX?

**Comment by simondotm** [comment]
> It doesn't live-reload changes or watch the functions directory, is there a way to fix that?

@seanaguinaga 
See #95
Closing this one.
